# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    # Look for `requirements.txt` and `setup.py` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      # Check for updates at 9am UTC on Monday
      time: "09:00"
      # Use Australia/Sydney timezone (UTC+10:00)
      timezone: "Australia/Sydney"
    # Auto-approve minor and patch updates
    labels:
      - "dependencies"
      - "automated"
    # Group updates by dependency name and widen version ranges
    versioning-strategy: "widen"
    # Open pull requests for version updates
    open-pull-requests-limit: 10
    # Only allow updates to the lockfile for security updates
    allow:
      - dependency-type: "direct"
    # Ignore major version updates for now
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for `.github/workflows/` for workflow files
    directory: "/"
    # Check for updates once a month
    schedule:
      interval: "monthly"
    labels:
      - "github-actions"
      - "dependencies"
      - "automated"
